### ISSUE TITLE
Continuously increasing memory consumption

### ISSUE THREAD

**Issue by RegDenied** [mustafakalash/royt#34] opened 2018-07-26 23:16 UTC
FF 61.01, royt 2.3.1
When playing a YT video the memory consumption increases constantly (about 1GB in 30s) until tab is closed or all is consumed, closing the tab releases it again.
Deactivating royt fixes the issue completely.
I assume this is related to a YT API change?

**Comment by ricterG** [comment] 2018-07-27 00:01
Getting the same issue, same build. And yeah youtube updated a bunch of stuff recently.

**Comment by zjeffer** [comment] 2018-07-27 12:08
Same issue, it goes to about 4GB for me

**Comment by Mecheye** [comment] 2018-07-27 13:40
Same issue. Mine got up to 11 gigs used memory.

I noticed it right after updating Java to the latest build. Maybe that has to do with it?

64 bit Win7

**Comment by mustafakalash** [comment] 2018-07-29 03:17
Are the comments also not displaying for all of you, as in #35, or are you just seeing an increase in memory usage?

You say there's been a YouTube update. I guess I'm just late to the roll out. I'll try to find a way to force it so that I can reproduce the issue, but if you know of any ways, please let me know. (EDIT: just loaded it up while signed out, can reproduce)

I will try to find the time to work on this thoroughly sometime next week.

Thanks for the report!

**Comment by oldmud0** [comment] 2018-08-01 03:02
Related Reddit thread: https://www.reddit.com/r/firefox/comments/92gtig/memory_leak_in_new_youtube_with_firefox_just_a/

Basically, YouTube switched to [Web Components](https://www.w3.org/standards/techs/components) which uses [Polymer](https://www.polymer-project.org/) for polyfills and some extra abstraction. Firefox still does not support a part of this standard, so polyfills are used instead, including for Shadow DOM (but probably will be enabled in Firefox 63).

I'm not sure either what could be causing the memory leak. Here is a snapshot that I took.
[15236785.fxsnapshot.gz](https://github.com/mustafakalash/royt/files/2247873/15236785.fxsnapshot.gz)

(note, this is not actually a .gz, the extension was added to let GitHub upload it here)

**Comment by Hannah-GBS** [comment] 2018-08-18 19:43
Any update on this?

**Comment by zjeffer** [comment] 2018-08-25 14:04
I temporarily fixed this with the Youtube Classic addon by 'thisdotvoid': https://github.com/thisdotvoid/youtube-classic-extension

**Comment by Hannah-GBS** [comment] 2018-08-25 19:39
Can confirm that works, though the lack of dark mode with that addon hurts my eyes.

A permanent fix for this is sorely needed.

**Comment by mustafakalash** [comment] 2018-08-30 14:12
I'm sorry, I'm extremely busy.

**Comment by merkle-root** [comment] 2018-09-04 03:36
@loldudester Try the extension Stylish and [pick a dark extension](https://userstyles.org/styles/browse/youtube).

**Comment by MagmaGuy** [comment] 2018-12-23 01:22
Necroposting because I really would love to see this fixed. There are currently no other options out there. It's the only reason I still have half a mind to switch back to Chrome even though I really don't want to.

**Comment by jacobsandersen** [comment] 2018-12-23 03:45
Here is a temporary download for ROYT that includes #38: https://addons.mozilla.org/en-US/firefox/addon/reddit-on-youtube-memfix/

**Closed as completed** 2018-12-23 15:44 UTC
