### ISSUE TITLE
Today's YouTube update broke RoYT

### ISSUE THREAD

**Issue by Atario** [mustafakalash/royt#35] opened 2018-07-27 22:48 UTC
No comments of any kind appear anymore…

**Comment by shelt** [comment] 2018-07-28 02:46
Also, very high CPU usage on any YT tab.

**Comment by zjeffer** [comment] 2018-07-28 12:13
Duplicate of #34

**Comment by mustafakalash** [comment] 2018-07-29 03:26
Closing as duplicate, but thanks for the report.

**Closed as completed by mustafakalash** 2018-07-29 03:26 UTC
